; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower

[env:pico2]
board = rpipico2
build_flags =
    -DNDEBUG
    -DJIANGTUN_CONFIG_BOARD_PICO
debug_tool = cmsis-dap

[env:dol-pico2]
board = rpipico2
build_flags =
    -DNDEBUG
    -DJIANGTUN_CONFIG_BOARD_PICO
    -DJIANGTUN_CONFIG_ENABLE_DOL
debug_tool = cmsis-dap

[env:xiao-rp2350]
board = seeed_xiao_rp2350
build_flags =
    -DNDEBUG
    -DJIANGTUN_CONFIG_BOARD_XIAO_RP2350
debug_tool = cmsis-dap

[env:dol-xiao-rp2350]
board = seeed_xiao_rp2350
build_flags =
    -DNDEBUG
    -DJIANGTUN_CONFIG_BOARD_XIAO_RP2350
    -DJIANGTUN_CONFIG_ENABLE_DOL
debug_tool = cmsis-dap
